#! /bin/sh

### BEGIN INIT INFO
# Provides:             fakecron
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    FakeCron
### END INIT INFO

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting Fake Cron" "fakecron" || true
        if start-stop-daemon --background --start --quiet --oknodo --pidfile /var/run/fakecron.pid --exec /usr/local/bin/fakecron.sh ; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  stop)
        log_daemon_msg "Stopping Fake Cron" "fakecron" || true
        if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/fakecron.pid; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        killall fakecron.sh &> /dev/null
        ;;

  status)
        status_of_proc -p /var/run/fakecron.pid /usr/local/bin/fakecron.sh fakecron && exit 0 || exit $?
        ;;

  *)
        log_action_msg "Unknown action!" || true
        exit 1
esac

exit 0