#! /bin/sh

### BEGIN INIT INFO
# Provides:             rfid_app
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    RFID APP START/STOP SCRIPT
### END INIT INFO

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting RFID APP" "rfid_app" || true
        if start-stop-daemon --background --start --quiet --oknodo --user root --chuid root --pidfile /var/run/rfid_app.pid --exec /usr/local/bin/rfid_app.sh ; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  stop)
        log_daemon_msg "Stopping RFID APP" "rfid_app" || true
        if start-stop-daemon --stop --quiet --oknodo --user root --chuid root --pidfile /var/run/rfid_app.pid; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        killall rfid_app.sh &> /dev/null
        ;;

  status)
        status_of_proc -p /var/run/rfid_app.pid /usr/local/bin/rfid_app.sh rfid_app && exit 0 || exit $?
        ;;

  *)
        log_action_msg "Unknown action!" || true
        exit 1
esac

exit 0
